
deploy-dev:
	terraform apply -var-file="variables/dev.tfvars" -auto-approve

deploy-test:
	terraform apply -var-file="variables/test.tfvars" -auto-approve

deploy-prod:
	terraform apply -var-file="variables/prod.tfvars" -auto-approve